naam = input("Wat is uw naam? ")
adres = input("Wat is uw adres?")
postcode = input("Wat is uw postcode? ")
woonplaats = input("Wat is uw woonplaats? ") 
pincode = input("Nu we toch bezig zijn mag ik ook uw pincode? ")