naam=input("Hallo, wat is je naam? ")
leeftijd=input(f"Goedemorge{naam}, hoe oud ben je? ")
eten=input(f"En als {leeftijd} jarige, wat eet je het liefst? ")
drinken= input(f"En wat drink je het liest bij {eten}? ")
print(f"De {leeftijd} jarige {naam} drinkt het liefst {drinken} bij {eten}")